name = "LinearMixingModels"
uuid = "b8ce4b42-e81b-4a39-a84a-67f74a9a16dd"
authors = ["Invenia Technical Computing Corporation"]
version = "0.1.4"

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AbstractGPs = "0.3, 0.5"
BlockDiagonals = "0.1.22"
ChainRulesCore = "1"
Distributions = "0.25"
FillArrays = "0.12"
KernelFunctions = "0.10"
julia = "1"
